---
# tasks file for ldapsearch_user

- name: "Create LDAPSearch user"
  block:
    - name: "Create LDAPSearch user for Nextcloud"
      ansible.builtin.command: >
        udm users/ldap create
          --position "cn=users,{{ ldapsearch_user_basedn }}"
          --set name="ldapsearchnc"
          --set username="ldapsearchnc"
          --set lastname="LDAPSearch-Nextcloud"
          --set password="{{ ldapsearch_user_nextcloud_password }}"
          --ignore_exists
      when: "'nextcloud' in ldapsearch_user_install_apps"
      tags:
        - ldapsearch_user_nextcloud

    - name: "Create LDAPSearch user for OX"
      ansible.builtin.command: >
        udm users/ldap create
          --position "cn=users,{{ ldapsearch_user_basedn }}"
          --set name="ldapsearchox"
          --set username="ldapsearchox"
          --set lastname="LDAPSearch-OpenXchange"
          --set password="{{ ldapsearch_user_ox_password }}"
          --ignore_exists
      when: "'oxseforucs' in ldapsearch_user_install_apps or 'ox-connector' in ldapsearch_user_install_apps"
      tags:
        - ldapsearch_user_nextcloud
  when: "ldapsearch_user_server_type|default('master') != 'backup'"
  tags:
    - ldapsearch_user
