---
# tasks file for ucs_add_admin_user

- name: "Add Admin User"
  ansible.builtin.command:
    argv:
      - "udm"
      - "users/user"
      - "create"
      - "--ignore_exists"
      - "--position"
      - "cn=users,{{ ucs_add_admin_user_basedn }}"
      - "--set"
      - "username={{ ucs_add_admin_user_username }}"
      - "--set"
      - "firstname={{ ucs_add_admin_user_firstname }}"
      - "--set"
      - "lastname={{ ucs_add_admin_user_lastname }}"
      - "--set"
      - "password={{ ucs_add_admin_user_password }}"
      - "--set"
      - "PasswordRecoveryEmail={{ ucs_add_admin_user_recoveryemail }}"
  tags:
    - ucs_add_admin_user
    - ucs_add_admin_user_add_user

- name: "Add Admin User to group Domain Admins"
  ansible.builtin.command:
    argv:
      - "udm"
      - "groups/group"
      - "modify"
      - "--dn"
      - "cn=Domain Admins,cn=groups,{{ ucs_add_admin_user_basedn }}"
      - "--append"
      - "users=uid={{ ucs_add_admin_user_username }},cn=users,{{ ucs_add_admin_user_basedn }}"
  tags:
    - ucs_add_admin_user
    - ucs_add_admin_user_add_to_group

- name: "Set primary group to Domain Admins"
  ansible.builtin.command:
    argv:
      - "udm"
      - "users/user"
      - "modify"
      - "--dn"
      - "uid={{ ucs_add_admin_user_username }},cn=users,{{ ucs_add_admin_user_basedn }}"
      - "--set"
      - "primaryGroup=cn=Domain Admins,cn=groups,{{ ucs_add_admin_user_basedn }}"
  tags:
    - ucs_add_admin_user
    - ucs_add_admin_user_set_primary_group

- name: "Trigger password recovery mail"
  no_log: true
  ansible.builtin.expect:
    command: umc-command passwordreset/send_token -o username={{ ucs_add_admin_user_username }} -o method=email
    responses:
      Username: "{{ ucs_add_admin_user_username }}"
      Password: "{{ ucs_add_admin_user_password }}"
  tags:
    - ucs_add_admin_user
    - ucs_add_admin_user_trigger_password_recovery