---
# tasks file for deployment_message

- name: "Check if all vars are set"
  ansible.builtin.assert:
    that:
      - deployment_message_external_hostname|length > 0
      - deployment_message_domain_name|length > 0
      - deployment_message_basedn|length > 0
      - deployment_message_server_type|length > 0
      - deployment_message_saml_config_type|length > 0
    fail_msg: "At least one necessary variable is not set. Skip this check with --skip-tags deployment_message_check_preconditions"
  tags:
    - deployment_message
    - deployment_message_check_preconditions

- name: "Load version info"
  ansible.builtin.include_vars:
    file: "version_info.yml"
    name: "deployment_message_custom_fact_deployment"
  ignore_errors: true
  tags:
    - deployment_message
    - deployment_message_version_info

- name: "Print Deployment Start Message"
  vars:
    deployment_message_message: "{{ lookup('template', 'deployment_start_message.j2') }}"
  ansible.builtin.debug:
    msg: "{{ deployment_message_message.split('\n') }}"
  when: "deployment_message_custom_fact_deployment is defined"
  tags:
    - deployment_message
    - deployment_message_print_version_info

- name: "Pause for {{ deployment_message_verification_pause_duration }} seconds"
  ansible.builtin.pause:
    seconds: "{{ deployment_message_verification_pause_duration }}"
  when: "deployment_message_custom_fact_deployment is defined"
  tags:
    - deployment_message
    - deployment_message_initial_pause
