---
# tasks file for portal_delete_entry

- name: "Check if entry that is about to be deactivated exists to begin with"
  ansible.builtin.command: >
    udm portals/entry list
    --position "cn=entry,{{ portal_delete_entry_item['dn']|default(portal_delete_entry_portal_dn) }}"
    --filter "cn={{ portal_delete_entry_item['name'] }}"
  loop: "{{ portal_delete_entry_entries|selectattr('state', 'defined')|selectattr('state', 'equalto', 'absent')
              |list|default([])|flatten }}"
  loop_control:
    loop_var: "portal_delete_entry_item"
  register: "portal_delete_entry_entries"
  when: |
    ('only' not in portal_delete_entry_item) or
    ('only' in portal_delete_entry_item and
      portal_delete_entry_install_list|intersect([portal_delete_entry_item['only']]|flatten)
    )
  tags:
    - "portal_delete_entry"
    - "portal_delete_entry_check_entries"

- name: "Delete existing portal entry"
  vars:
    entry: "{{ portal_delete_entry_item.item }}"
  ansible.builtin.command: >
    udm portals/entry delete
    --dn 'cn={{ entry["name"] }},cn=entry,{{ entry["dn"]|default(portal_delete_entry_portal_dn) }}'
    --ignore_not_exists
  loop: "{{ portal_delete_entry_entries['results']|default([]) }}"
  loop_control:
    loop_var: "portal_delete_entry_item"
  tags:
    - "portal_delete_entry"
    - "portal_delete_entry_delete_entry"
