---
# tasks file for portal_create_category

- name: "Get a list of already existing categories"
  ansible.builtin.command: >
    udm portals/category list
    --position "cn=category,{{ portal_create_category_portal_dn }}"
  changed_when: false
  register: "portal_create_category_categories_portal_categories"
  tags:
    - "portal_create_category"
    - "portal_create_category_check_categories"

- name: "Create portal category"
  vars:
    portal_create_category_categories_portal_existing: "
      {{ portal_create_category_categories_portal_categories['stdout_lines']
          |regex_findall('cn=[a-zA-Z-]+')|map('regex_replace', '^cn=(.*)$', '\\1')|list|unique|lower }}"
  ansible.builtin.command: >
    udm portals/category
    {% if portal_create_category_item['name']|lower in portal_create_category_categories_portal_existing %}
    modify
    --dn cn={{ portal_create_category_item['name'] }},cn=category,{{ portal_create_category_portal_dn }}
    {% for lang, text in (portal_create_category_item['display_name']|default({})).items() %}
    --append displayName='{{ lang }} "{{ text }}"'
    {% endfor %}
    {% else %}
    create
    --ignore_exists
    --position cn=category,{{ portal_create_category_portal_dn }}
    {% for lang, text in (portal_create_category_item['display_name']|default({})).items() %}
    --append displayName='{{ lang }} "{{ text }}"'
    {% endfor %}
    --set name='{{ portal_create_category_item['name'] }}'
    {% endif %}
  changed_when: "portal_create_category_add_category_result.stdout is not search('No modification')"
  loop: "{{ [portal_create_category_categories|selectattr('state', 'defined')
              |selectattr('state', 'equalto', 'present')|list|default([])|flatten,
             portal_create_category_categories|selectattr('state', 'undefined')|list|default([])|flatten]|flatten }}"
  loop_control:
    loop_var: "portal_create_category_item"
  register: "portal_create_category_add_category_result"
  when: |
    ('only' not in category) or
    ('only' in portal_create_category_item and
      portal_create_category_install_list|intersect([portal_create_category_item['only']]|flatten)
    )
  tags:
    - "portal_create_category"
    - "portal_create_category_add_category"

- name: "Append category to portal categories list"
  ansible.builtin.command:
    argv:
      - "udm"
      - "portals/portal"
      - "modify"
      - "--dn"
      - "cn=domain,cn=portal,{{ portal_create_category_portal_dn }}"
      - "--append"
      - "categories=cn={{ portal_create_category_item['name'] }},cn=category,{{ portal_create_category_portal_dn }}"
  changed_when: "portal_create_category_append_category_result.stdout is not search('No modification')"
  loop: "{{ portal_create_category_categories|selectattr('state', 'equalto', 'present')|default([])|flatten }}"
  loop_control:
    loop_var: "portal_create_category_item"
  register: "portal_create_category_append_category_result"
  tags:
    - "portal_create_category"
    - "portal_create_category_append_category"
