---
# tasks file for configure_monitoring

- name: "configure_monitoring | Configure LDAP monitor"
  univention.ucs_modules.univention_config_registry:
    keys:
      ldap/monitor: "{{ configure_monitoring_ldap_enabled|default('true') }}"
  tags:
    - "configure_monitoring"
    - "configure_monitoring_ldap"
