---

- example: "Installed: letsencrypt=1.2.2-8 mailserver=12.0 nextcloud=20.0.2-0 onlyoffice-ds=6.1.0.83"
  getval: |
    (?x)
    (^In\S+:\s)
    (?P<applist>.+$)
  result:
    univention_app_list: "{{ applist.split() }}"
