---
# tasks file for remove_packages

- name: "Remove Univention app packages"
  vars:
    remove_packages_package_version: "{{ '=' + remove_packages_app_version_map[item]
          if item in remove_packages_app_version_map
          else '' }}"
    remove_packages_package_name: "{{ remove_packages_service_name_list[item]|default(item) }}"
  ansible.builtin.command: "univention-app remove {{ remove_packages_package_name }} --noninteractive --pwdfile {{ remove_packages_temp_pw_file.path }}"
  loop: "{{ remove_packages_remove_apps }}"
  when: remove_packages_package_name in remove_packages_currently_installed_apps and
        remove_packages_force_package_upgrade|bool and
        (remove_packages_package_version != '') and
        (remove_packages_currently_installed_apps[package_name] != remove_packages_package_version[1:])
  register: remove_packages_package_removal
  retries: 10
  delay: 10
  until: "remove_packages_package_removal.rc == 0"
  tags:
    - run_letsencrypt_script_install_app