---
# handlers file for configure_office_suite

- name: "Restart collabora-online"
  ansible.builtin.shell: "univention-app stop collabora-online; univention-app start collabora-online"
  ignore_errors: true