---
# tasks file for cleanup_portal

- name: "cleanup_portal | Install Dashboard"
  block:
    - name: "Allow Domain Admin group access to dashboard features"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/entry"
          - "modify"
          - "--dn"
          - "{{ cleanup_portal_item }}"
          - "--set"
          - "allowedGroups={{ cleanup_portal_domain_admin_group }}"
      loop:
        - "{{ cleanup_portal_prometheus_dn }}"
        - "{{ cleanup_portal_admin_dashboard_dn }}"
      loop_control:
        loop_var: "cleanup_portal_item"
      tags:
        - "cleanup_portal_domain_admin_permissions"

    - name: "cleanup_portal | Add portal entries to Administration category"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/category"
          - "modify"
          - "--dn"
          - "cn=Administration,cn=category,{{ cleanup_portal_portal_dn }}"
          - "--append"
          - "{{ cleanup_portal_prometheus_dn }}"
          - "--append"
          - "{{ cleanup_portal_admin_dashboard_dn }}"
      tags:
        - "cleanup_portal_add_portal_entries"
    - name: "cleanup_portal | Remove portal entries from domain admin category"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/category"
          - "modify"
          - "--dn"
          - "cn=domain-admin,cn=category,{{ cleanup_portal_portal_dn }}"
          - "--remove"
          - "{{ cleanup_portal_prometheus_dn }}"
          - "--remove"
          - "{{ cleanup_portal_admin_dashboard_dn }}"
      tags:
        - "cleanup_portal_remove_portal_entries"

    - name: "cleanup_portal | Deactivate portal entries"
      ansible.builtin.command:
        argv:
          - "udm"
          - "portals/entry"
          - "modify"
          - "--dn"
          - "{{ cleanup_portal_item }}"
          - "--set"
          - "activated=FALSE"
      loop:
        - "{{ cleanup_portal_prometheus_dn }}"
        - "{{ cleanup_portal_admin_dashboard_dn }}"
      loop_control:
        loop_var: "cleanup_portal_item"
      tags:
        - "cleanup_portal_deactivate_portal_entries"
  when: "'dashboard' in cleanup_portal_install_services"
  tags:
    - "cleanup_portal"
