---
# tasks file for umc_permissions

- name: "Hide remaining UMC modules per UCR and empty favorites"
  univention.ucs_modules.univention_config_registry:
    keys:
      umc/module/udm/oxresources/oxresources/disabled: true
      umc/module/udm/oxmail/oxmail/disabled: true
      umc/web/favorites/default: ""
  tags:
    - umc_permissions
    - umc_permissions_ucr

- name: "Manage cn=only-users-and-groups,cn=UMC,cn=policies"
  block:
    - name: "Remove policies/umc"
      ansible.builtin.command:
        argv:
          - "udm"
          - "policies/umc"
          - "delete"
          - "--dn"
          - "cn=only-users-and-groups,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
      ignore_errors: true
      tags:
        - umc_permissions_policy_remove

    - name: "Add policies/umc"
      ansible.builtin.command:
        argv:
          - "udm"
          - "policies/umc"
          - "create"
          - "--position=cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
          - "--set"
          - "name=only-users-and-groups"
          - "--append"
          - "allow=cn=udm-users,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
          - "--append"
          - "allow=cn=udm-groups,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
          - "--append"
          - "allow=cn=udm-new-portal,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      tags:
        - umc_permissions_policy_add

    - name: "Add policy reference"
      ansible.builtin.command:
        argv:
          - "udm"
          - "groups/group"
          - "modify"
          - "--dn"
          - "cn=Domain Admins,cn=groups,{{ umc_permissions_basedn }}"
          - "--policy-dereference"
          - "cn=default-umc-all,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
          - "--policy-reference"
          - "cn=only-users-and-groups,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
      ignore_errors: true
      tags:
        - umc_permissions_policy_add_reference
  tags:
    - umc_permissions
    - umc_permissions_policy

- name: "Manage cn=udm-usertemplates,cn=operations,cn=UMC,cn=univention"
  block:
    - name: "Remove settings/umc_operationset"
      ansible.builtin.command:
        argv:
          - "udm"
          - "settings/umc_operationset"
          - "delete"
          - "--dn"
          - "cn=udm-usertemplates,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      ignore_errors: true
      tags:
        - umc_permissions_policy_usertemplate_remove_settings

    - name: "Remove from policies/umc"
      ansible.builtin.command:
        argv:
          - "udm"
          - "policies/umc"
          - "modify"
          - "--dn"
          - "cn=only-users-and-groups,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
          - "--remove"
          - "allow=cn=udm-usertemplates,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      ignore_errors: true
      tags:
        - umc_permissions_policy_usertemplate_remove_policy

    - name: "Add settings/umc_operationset"
      ansible.builtin.command:
        argv:
          - "udm"
          - "settings/umc_operationset"
          - "create"
          - "--position=cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
          - "--set"
          - "name=udm-usertemplates"
          - "--set"
          - "description=UDM - Usertemplates"
          - "--set"
          - "flavor=settings/usertemplate"
          - "--set"
          - "operation=udm/*"
      tags:
        - umc_permissions_policy_usertemplate_add_settings

    - name: "Add to policies/umc"
      ansible.builtin.command:
        argv:
          - "udm"
          - "policies/umc"
          - "modify"
          - "--dn"
          - "cn=only-users-and-groups,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
          - "--append"
          - "allow=cn=udm-usertemplates,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      tags:
        - umc_permissions_policy_usertemplate_add_policy
  tags:
    - umc_permissions
    - umc_permissions_policy_usertemplate

- name: "Manage cn=udm-reports,cn=operations,cn=UMC,cn=univention"
  block:
    - name: "Remove settings/umc_operationset"
      ansible.builtin.command:
        argv:
          - "udm"
          - "settings/umc_operationset"
          - "delete"
          - "--dn"
          - "cn=udm-reports,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      ignore_errors: true
      tags:
        - umc_permissions_policy_userreports_remove_settings

    - name: "Remove from policies/umc"
      ansible.builtin.command:
        argv:
          - "udm"
          - "policies/umc"
          - "modify"
          - "--dn"
          - "cn=only-users-and-groups,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
          - "--remove"
          - "allow=cn=udm-reports,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      ignore_errors: true
      tags:
        - umc_permissions_policy_userreports_remove_policy

    - name: "Add settings/umc_operationset"
      ansible.builtin.command:
        argv:
          - "udm"
          - "settings/umc_operationset"
          - "create"
          - "--position=cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
          - "--set"
          - "name=udm-reports"
          - "--set"
          - "description=UDM - User Reports"
          - "--set"
          - "operation=udm/reports/get"
      tags:
        - umc_permissions_policy_userreports_add_settings

    - name: "Add to policies/umc"
      ansible.builtin.command:
        argv:
          - "udm"
          - "policies/umc"
          - "modify"
          - "--dn"
          - "cn=only-users-and-groups,cn=UMC,cn=policies,{{ umc_permissions_basedn }}"
          - "--append"
          - "allow=cn=udm-reports,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      tags:
        - umc_permissions_policy_userreports_add_policy
  tags:
    - umc_permissions
    - umc_permissions_policy_userreports

- name: "Allow groups to be added to user"
  ansible.builtin.command:
    argv:
      - "udm"
      - "settings/umc_operationset"
      - "modify"
      - "--dn"
      - "cn=udm-users,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      - "--append"
      - "operation=udm/syntax/choices:objectType=groups/group"
  tags:
    - umc_permissions
    - umc_permissions_allow_groups_add_to_users

- name: "Allow users to be added to groups"
  ansible.builtin.command:
    argv:
      - "udm"
      - "settings/umc_operationset"
      - "modify"
      - "--dn"
      - "cn=udm-groups,cn=operations,cn=UMC,cn=univention,{{ umc_permissions_basedn }}"
      - "--append"
      - "operation=udm/syntax/choices:objectType=users/user"
  tags:
    - umc_permissions
    - umc_permissions_allow_users_add_to_groups

- name: "Remove any from passwordreset/blacklist"
  univention.ucs_modules.univention_config_registry:
    keys:
      umc/self-service/passwordreset/blacklist/groups: "{{ umc_permissions_passwordreset_blacklist_groups }}"
  tags:
    - umc_permissions
    - umc_permissions_policy_selfservice_blacklist
