---
# tasks file for install_univention

- name: "Install via univention-install"
  ansible.builtin.command: "univention-install --yes {{ install_univention_install_name }}"
  register: install_univention_install
  retries: 10
  delay: 10
  until: "install_univention_install.rc == 0"
  tags:
    - install_univention_install
