---
# handlers file for configure_apps_postfix

- name: "Restart postfix"
  ansible.builtin.service:
    name: "postfix"
    state: "restarted"
  tags:
    - "configure_apps_postfix"
    - "configure_apps_postfix_restart_postfix"
